name: Generate Tokyo Data 
on: 
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
    
jobs:
  generate-tokyo:
    name: summarize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install
        
      - name: Generate tokyo/counts.json 
        run: node generate_tokyo.js

      - name: Git Status
        run: git status

      - name: Commit files
        run: |
          git config --local user.email alastair+automated@liquidx.net
          git config --local user.name "Automated Action"
          git add docs/tokyo/counts.json
          git commit -m "Automated Data Update: Tokyo" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
